
'''MUST USE OWN SPOTIFY ACCOUNT.
-FIRST GO TO THE DEVELOPER DASHBOARD AND CREATE A NEW SPOTIFY APP.
-AFTER CREATING A SPOTIFY APP, COPY THE CLIENT ID AND CLIENT SECRET.
'''
CLIENT_ID = "ENTER CLIENT ID"
CLIENT_SECRET = "ENTER CLIENT SECRET"
SPOTIPY_REDIRECT_URI= "http://example.com"
SPOTIFY_URI = []

'''ASK USER FOR THEIR DATE PREFERENCE AND RETURN THE TOP 100 BILLBOARD SONGS ON THAT SPECIFIC DATE 
THE USER CHOSE USING BEAUTFULSOUP '''
user_input = input("Which year do you want to travel to? Please enter the date in this format YYYY-MM-DD:\n")

